#! /bin/bash

if type dnf > /dev/null; then
	sudo dnf groupinstall  -y 'Development Tools'

	sudo dnf install -y \
		git \
		libxcrypt-compat
fi

if type apt-get > /dev/null; then
	sudo apt-get update -y

	sudo apt-get install -y \
		git \
		build-essential \
		man
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


brew install gcc #gcc to help build some of the main pkgs

brew install \
	antibody \
	bat \
	chezmoi \
	diff-so-fancy \
	dos2unix \
	entr \
	exa \
	fd \
	file \
	fzf \
	git \
	httpie \
	hyperfine \
	jq \
	npm \
	parallel \
	rust \
	shellcheck \
	the_silver_searcher \
	tldr \
	tmux \
	unzip \
	wget \
	zsh

brew install python #install python alone seems to help w/ pip3, not sure why

brew install beeftornado/rmtree/brew-rmtree
brew install sschlesier/bombardier/bombardier
brew install sschlesier/csvutils/csvquote

pip3 install \
	visidata \
	openpyxl \
	pylint

npm install -g \
	log-color-highlight \
	markserv \
	npm-check

cargo install dua-cli
