#! /usr/bin/env sh

chezmoi init https://github.com/sschlesier/dotfiles-chezmoi.git
email=$( echo which email do you want to use? >&2 && \
printf "scotts@iqmetrix.com\nscott@schlesier.ca" | fzf)
if [ "$email" != scott@schlesier.ca ]; then
	sed -i.bak "s/scott@schlesier.ca/$email/g" ~/.config/chezmoi/chezmoi.toml
fi
chezmoi apply

chezmoi source -- remote remove origin
chezmoi source -- remote add origin git@github.com:sschlesier/dotfiles-chezmoi.git
# need ssh keys before fetch and setting upstream
# chezmoi source -- fetch origin
# chezmoi source -- branch --set-upstream-to=origin/master master

#create ~/.ssh so ssh-agent doesn't whine
mkdir -p ~/.ssh
