#! /usr/bin/env sh

curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-bootstrap | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-chezmoi | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-antibody | zsh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-vimplug | zsh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-tmux | zsh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/master/shell-manual-install | zsh
