#! /usr/bin/env sh

if type dnf > /dev/null; then
  sudo dnf -y group install \
	Core

  sudo dnf -y install \
	acpi \
	bind-utils \
	dos2unix \
	exa \
	file \
	fd-find \
	fzf \
	git \
	hyperfine \
	httpie \
	jq \
	man \
	neovim \
	npm \
	p7zip-plugins \
	parallel \
	plantuml \
	python python-pip \
	python3 python3-pip \
	ruby \
	the_silver_searcher \
	tmux \
	unzip \
	wget \
	zsh

  sudo dnf -y module install \
	bat

  sudo npm install -g \
	log-color-highlight \
	markserv \
	npm-check
else
	echo only dnf based systems supported
	exit 1
fi
