#! /usr/bin/env zsh

#install rust and cargo
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

~/.cargo/bin/cargo install dua-cli
~/.cargo/bin/cargo install du-dust
~/.cargo/bin/cargo install verco
