#! /bin/sh

curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/brewfile/shell-bootstrap | sh
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/brewfile/shell-chezmoi | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/brewfile/shell-antibody | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/brewfile/shell-vimplug | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/brewfile/shell-tmux | sh
