#! /bin/sh

curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-bootstrap | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-chezmoi | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-antibody | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-vimplug | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-tmux | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-cargo | sh
curl -sfL https://raw.githubusercontent.com/sschlesier/shell-setup/main/shell-manual-install | sh
