#! /usr/bin/env sh

#setup defaault ssh config
curl --fail --silent --show-error --location \
	--output ~/.ssh/config https://gist.githubusercontent.com/sschlesier/128b3c59ed82034d2fc983ecabdfb4ea/raw/config
chmod 644 ~/.ssh/config
