#! /bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

sudo	apt-get update -y
sudo	apt-get install -y \
		build-essential

brew install gcc #gcc to help build some of the main pkgs

brew install \
	bat \
	dos2unix \
	entr \
	exa \
	fd \
	file \
	fzf \
	git \
	httpie \
	hyperfine \
	jq \
	lastpass-cli \
	moreutils \
	neovim \
	npm \
	plantuml \
	python \
	ranger \
	the_silver_searcher \
	tmux \
	unzip \
	wget \
	zsh

pip3 install \
	visidata

npm install -g \
	log-color-highlight \
	markserv \
	npm-check
