#! /usr/bin/env sh

if type pkg > /dev/null; then
  pkg install \
	atool \
	bat \
	bombardier \
	diff-so-fancy \
	entr \
	exa \
	fd-find \
	file \
	fzf \
	git \
	grv \
	hyperfine \
	jq \
	lastpass-cli \
	moreutils \
	neovim \
	npm \
	parallel \
	py37-httpie \
	py37-pip \
	py37-ranger \
	python37 \
	ripgrep \
	tealdeer \
	the_silver_searcher \
	tmux \
	unzip \
	wget \
	youtube_dl \
	zsh

  npm install -g \
	log-color-highlight \
	markserv \
	npm-check
else
	echo only dnf based systems supported
	exit 1
fi
