#! /bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

sudo apt-get install build-essential

brew install \
	bat \
	dos2unix \
	entr \
	exa \
	fd \
	file \
	fzf \
	gcc \
	git \
	httpie \
	hyperfine \
	jq \
	lastpass-cli \
	moreutils \
	neovim \
	npm \
	parallel \
	plantuml \
	python \
	ranger \
	the_silver_searcher \
	tmux \
	unzip \
	wget \
	zsh

pip3 install \
	visidata

npm install -g \
	log-color-highlight \
	markserv \
	npm-check
